ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-alpine AS build

WORKDIR /app

ARG PUBLIC_SERVER_URL
ARG PUBLIC_WEBSOCKET_URL

ENV PUBLIC_SERVER_URL=$PUBLIC_SERVER_URL
ENV PUBLIC_WEBSOCKET_URL=$PUBLIC_WEBSOCKET_URL

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY docker/nginx.default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]